#:import theme theme

<Card>

    padding: "16dp"
    spacing: "8dp"

    canvas.before:

        Color:
            rgba: theme.COR_FUNDO_PAINEL_RGBA

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [8]

        Color:
            rgba: theme.COR_BORDA_RGBA

        Line:
            rounded_rectangle:
                (self.x,
                 self.y,
                 self.width,
                 self.height,
                 8)